### ISSUE TITLE
无法打开带箭头的文件夹，比如desciption下的unitree-ros

### ISSUE THREAD

**Issue by xiaoxioali** [skywoodsz/LVI-SAM-Quadruped#1]

**Comment by skywoodsz** [comment]
@xiaoxioali 

They are submodules of the repository. You can use the command `git clone —-recursive` to clone and install all dependencies.

**Comment by xiaoxioali** [comment]
我使用了git clone https://github.com/skywoodsz/LVI-SAM-Quadruped.git --recursive，但是仍未下载到依赖。

**Comment by xiaoxioali** [comment]
请问可否提供desciption下的unitree-ros的源码文件

**Comment by skywoodsz** [comment]
@xiaoxioali 
Some problems occurred while uploading the file.
You can download submodules from:
https://github.com/chvmp/champ_teleop
https://github.com/chvmp/robots
https://github.com/chvmp/yocs_velocity_smoother

**Comment by skywoodsz** [comment]
@xiaoxioali 
I have renewed the repository.
